#----------------------------------------------------------------------------
# Makefile for marrinator and projects
#----------------------------------------------------------------------------

include config.mk
include $(M8R_SRC_DIR)/shared.mk

build: ar

