#----------------------------------------------------------------------------
# Makefile for marrinator and projects
#----------------------------------------------------------------------------

include config.mk

debug release:
	make $@ -C $(M8R_SRC_DIR)

