#----------------------------------------------------------------------------
# Makefile for marrinator and projects
#----------------------------------------------------------------------------

default: begin build_app end

program: begin program_app end

include config.mk
include $(M8R_SRC_DIR)/shared.mk

.PHONY : default program

